#devtools::install_github("grunwaldlab/demulticoder", force=TRUE)
rcmdcheck::rcmdcheck(args = "--as-cran")
#devtools::clean_dll()
#devtools::install_github("grunwaldlab/demulticoder", force=TRUE)
devtools::load_all("~/demulticoder")
library("demulticoder")
devtools::document()

install.packages("pkgdown")
library("pkgdown")
pkgdown::build_site(check = FALSE)
install.packages(c("metacoder", "sessioninfo", "pkgdown"))
library("metacoder")
library("sessioninfo")
library("pkgdown")
pkgdown::build_site()
install.packages("dplyr")
library("dplyr")
